services:
  dockerd-exporter:
    image: ${IMAGE_NAME:-caddy}:${IMAGE_TAG:-latest}
    environment:
      CADDY_PORT:
      DOCKER_GWBRIDGE_IP:
      DOCKER_GWBRIDGE_PORT:
    networks:
      metric-net:
    configs:
      - source: caddyfile-config
        target: /etc/caddy/Caddyfile
    healthcheck:
      test: wget --spider -q http://127.0.0.1:${CADDY_PORT}/health
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-5s}
      retries: ${HEALTHCHECK_RETRIES:-10}
      start_period: ${HEALTHCHECK_START_PERIOD:-30s}
    deploy:
      mode: global
      restart_policy:
        delay: ${RESTART_DELAY:-5s}
      update_config:
        delay: ${UPDATE_DELAY:-0s}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-32M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-16M}

networks:
  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    driver: ${METRIC_NET_DRIVER:-overlay}
    external: true

configs:
  caddyfile-config:
    name: ${CADDYFILE_CONFIG_NAME:-dockerd-exporter-caddyfile}
    file: ./config/Caddyfile
